AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Este stack va a crear
  una instancia y todo lo 
  que necesita

Resources:
  
  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite el acceso al puerto 22"
      GroupName: "SSHSecurityGroup"
      VpcId: "vpc-0f7a5d7c9505d586c"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0c7217cdde317cfec"
      InstanceType: "t2.micro"
      KeyName: "practicacloudformation"
      SecurityGroupIds:
        - Ref: "SecurityGroupSSH"