AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Este stack va a crear
  una instancia y todo lo 
  que necesita

Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: "pem"
      KeyName: "keypair-pruebas-cf"
      KeyType: "ed25519"
  
  myVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    EnableDnsSupport: 'true'
    EnableDnsHostnames: 'true'

  SecurityGroupSSH:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "Permite el acceso al puerto 22"
    GroupName: "SSHSecurityGroup"
    VpcId: !Ref myVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
    SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/o

  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0c7217cdde317cfec"
      InstanceType: "t2.micro"
      KeyName: !Ref "NewKeyPair"
  