AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Este stack va a crear
  una instancia y todo lo 
  que necesita

Resources:
  NewKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: keypair-pruebas-cf

  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0c7217cdde317cfec"
      KeyName: !Ref keypair-pruebas-cf